# SSHD Configuration for Integration Tests
# This file is generated by CMake and used to configure the SSHD server
# for integration tests.

# Instances will listen on different ports as specified in the test setup.
ListenAddress 127.0.0.1:@SSHD_PORT@

# Disable DNS lookups for faster connections in tests
UseDNS no

# Specify the location of host keys
HostKey @DATA_DIR@/@SSHD_INSTANCE_NAME@_rsa
HostKey @DATA_DIR@/@SSHD_INSTANCE_NAME@_ecdsa256
HostKey @DATA_DIR@/@SSHD_INSTANCE_NAME@_ecdsa384
HostKey @DATA_DIR@/@SSHD_INSTANCE_NAME@_ecdsa521
HostKey @DATA_DIR@/@SSHD_INSTANCE_NAME@_ed25519
# Specify the location of the PID file
PidFile @DATA_DIR@/@SSHD_INSTANCE_NAME@_sshd.pid

# Specify the location of the authorized keys file
AuthorizedKeysFile @DATA_DIR@/authorized_keys
# Use only public key authentication for tests
# Disable other authentication methods
ChallengeResponseAuthentication no
PasswordAuthentication no
UsePAM no
PermitRootLogin no
PubkeyAuthentication yes

# Specify the allowed Host Key Algorithms
HostKeyAlgorithms +ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519

# Environment variables for the test environment
SetEnv HOME=@DATA_DIR@/home LD_PRELOAD=@DATA_DIR@/libhome_replace.so FAKE_HOME=@DATA_DIR@/home
