# SSHD Configuration for Integration Tests
# This file is generated by CMake and used to configure the SSHD server
# for integration tests.

# Instances will listen on different ports as specified in the test setup.
ListenAddress 127.0.0.1:${SSH_PORT}

# Disable DNS lookups for faster connections in tests
UseDNS no

# Specify the location of host keys
HostKey ${CMAKE_CURRENT_BINARY_DIR}/${HOST_NAME}/host_rsa
HostKey ${CMAKE_CURRENT_BINARY_DIR}/${HOST_NAME}/host_ecdsa256
HostKey ${CMAKE_CURRENT_BINARY_DIR}/${HOST_NAME}/host_ecdsa384
HostKey ${CMAKE_CURRENT_BINARY_DIR}/${HOST_NAME}/host_ecdsa521
HostKey ${CMAKE_CURRENT_BINARY_DIR}/${HOST_NAME}/host_ed25519

# Specify the location of the PID file
PidFile ${CMAKE_CURRENT_BINARY_DIR}/${HOST_NAME}/sshd.pid

# Specify the location of the authorized keys file
AuthorizedKeysFile ${CMAKE_CURRENT_BINARY_DIR}/home/.ssh/authorized_keys
# Use only public key authentication for tests
# Disable other authentication methods
ChallengeResponseAuthentication no
PasswordAuthentication no
UsePAM no
PermitRootLogin no
PubkeyAuthentication yes

# Specify the allowed Host Key Algorithms
HostKeyAlgorithms +ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519

# Environment variables for the test environment
SetEnv HOME=${CMAKE_CURRENT_BINARY_DIR}/home LD_PRELOAD=${CMAKE_CURRENT_BINARY_DIR}/libhome_replace.so FAKE_HOME=${CMAKE_CURRENT_BINARY_DIR}/home
